name: CI/CD - Deploy FastAPI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSHPass
        run: sudo apt-get install -y sshpass

      - name: Deploy via SSH
        run: |
          sshpass -p "${{ secrets.SERVER_PASS }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << EOF
            cd fastapi-book-project
            git stash
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            # Restart FastAPI service
            sudo systemctl restart fastapi-dev-tonia
          EOF
