name: Deploy FastAPI

on:
  workflow_run:
    workflows: ["Test FastAPI"] # Must match the name in test.yml
    types:
      - completed

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # Ensures deploy runs only if tests pass
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASS }}
          script: |
            cd fastapi-book-project
            git stash
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            # Restart FastAPI service (now passwordless)
            sudo systemctl restart fastapi-dev-tonia
