name: CI/CD - Deploy FastAPI

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSHPass
        run: sudo apt-get install -y sshpass

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASS }}
          script: |
            cd fastapi-book-project
            git stash
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            # Restart FastAPI service
            sudo systemctl restart fastapi-dev-tonia
