name: test # The name that appears in your GitHub Actions tab

on: # Defines when this workflow runs
  push:
    branches: [main] # Runs when code is pushed to main branch
  pull_request:
    branches: [main] # Runs when a PR is created to main branch

jobs: # The actual work to be done
  test: # This job is named "test"
    runs-on: ubuntu-latest # Uses the latest Ubuntu virtual machine

    steps: # Sequential steps to execute
      - uses: actions/checkout@v2 # Clones your repository code

      - name: Set up Python # Sets up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.9" # Specifies Python version

      - name: Install dependencies # Installs required packages
        run: |
          python -m pip install --upgrade pip  # Updates pip
          pip install -r requirements.txt  # Installs project dependencies

      - name: Run tests # Executes your test suite
        run: |
          pytest
